server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  server:
    eviction-interval-timer-in-ms: 1000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
