spring:
  application:
    name: driver-service
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:test_22}
server:
  port: ${SERVER_PORT:8082}

eureka:
  instance:
    preferIpAddress: false
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
